from typing import Literal

WEBSOCKET_OPENED = "WEBSOCKET_OPENED"
WEBSOCKET_CLOSED = "WEBSOCKET_CLOSED"
WEBSOCKET_AUTHENTICATED = "WEBSOCKET_AUTHENTICATED"
Status = Literal[WEBSOCKET_OPENED, WEBSOCKET_CLOSED, WEBSOCKET_AUTHENTICATED]
